# Generated by Django 3.2.4 on 2021-06-17 17:02

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')
    # retorna uma instancia de model relativa a ultima migration que foi aplicada(nao retorna referente ao modelo
    # do meu models.py)
    # parametros acima sao da app "modulos" do modelo "Modulo"
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.title)   # editando cada registro
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_modulo_slug'),
    ]
    # isso informa ao framework de migração o que vamos fazer
    operations = [
        migrations.RunPython(popular_slug)  # nao execute a função, mas passe a função
    ]
